---
title: "Inter Rater Estimations"
author: "Anonymous"
date: "1 9 2020"
output: 
  html_document:
    theme: sandstone
editor_options: 
  chunk_output_type: console
---



```{r setup, include=TRUE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```



This doc gives some exploratory insight into the Themes and Expertise


```{r  include=FALSE}

# Setup: Always Run!
# This gets all packages and the file.

if(!require(tidyverse)){install.packages('tidyverse')}
if(!require(readxl)){install.packages('readxl')}
if(!require(summarytools)){install.packages('summarytools')}
if(!require(patchwork)){install.packages('patchwork')}
if(!require(ggsignif)){install.packages('ggsignif')}
if(!require(reshape2)){install.packages('reshape2')}
if(!require(viridis)){install.packages("viridis")}
library(tidyverse, summarytools)
library(readxl)
library(patchwork)
library(ggsignif)
library(reshape2)
library(viridis)
##Set Working DIR so Input&Output is correct
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

```


```{r}
#Import Data Set
##Note: This requires the complete Analysis Folder

#Get Thmese
InterRater_DF <- read_xlsx("Copy_of_CA_DummyCode_2coders.xlsx")

#Fix Naming Errors
InterRater_DF <- InterRater_DF %>%
  rename("Other meaning_2" = `Other thoughts and  meaning_2`)

```


```{r}
#Correlations 
CorVisualArt <- round(cor(InterRater_DF$`Visual Art`, InterRater_DF$`Visual Art_2`, method="pearson"),2)

CorMusic <- round(cor(InterRater_DF$`Music`, InterRater_DF$`Music_2`, method="pearson"),2)

CorOtherPerceptions <- round(cor(InterRater_DF$`Other perceptions`, InterRater_DF$`Other perceptions_2`, method="pearson"),2)

CorWellThoughtoutStory <- round(cor(InterRater_DF$`Well-thoughtout story, good writing`, InterRater_DF$`Well-thoughtout story, good writing_2`, method="pearson"),2)

CorStorytelling <- round(cor(InterRater_DF$Storytelling, InterRater_DF$Storytelling_2, method="pearson"),2)

CorSpecificThemes <- round(cor(InterRater_DF$`Addressing specific themes`, InterRater_DF$`Addressing specific themes_2`, method="pearson"),2)

CorCharacters <- round(cor(InterRater_DF$`Well-thoughtout characters`, InterRater_DF$`Well-thoughtout characters_2`, method="pearson"),2)

CorInteractivity <- round(cor(InterRater_DF$`Interactivity is key`, InterRater_DF$`Interactivity is key_2`, method="pearson"),2)

CorSimple <- round(cor(InterRater_DF$`Simple gameplay`, InterRater_DF$`Simple gameplay_2`, method="pearson"),2)

CorCraftsmanship <- round(cor(InterRater_DF$Craftsmanship, InterRater_DF$Craftsmanship_2, method="pearson"),2)

CorGameCharacters <- round(cor(InterRater_DF$`Game characters`, InterRater_DF$`Game characters_2`, method="pearson"),2)

CorOtherPeople <- round(cor(InterRater_DF$`Other people_2`, InterRater_DF$`Other people`, method="pearson"),2)

CorGame <- round(cor(InterRater_DF$Game, InterRater_DF$Game_2, method="pearson"),2)

CorUniqueExperience <- round(cor(InterRater_DF$`Unique experience`, InterRater_DF$`Unique experience_2`, method="pearson"),2)

CorHardToDescribe <- round(cor(InterRater_DF$`Hard-to-describe`, InterRater_DF$`Hard-to-describe_2`, method="pearson"),2)

CorPhysicalReactions <- round(cor(InterRater_DF$`Physical reactions`, InterRater_DF$`Physical reactions_2`, method="pearson"),2)

CorBehavior <- round(cor(InterRater_DF$`Behaviour/actions`, InterRater_DF$`Behaviour/actions_2`, method="pearson"),2)

CorIntenseEmotions <- round(cor(InterRater_DF$`Intense/powerful emotions`, InterRater_DF$`Intense/powerful emotions_2`, method="pearson"),2)

CorConflictingEmotions <- round(cor(InterRater_DF$`Conflicting feelings/mixed feelings`, InterRater_DF$`Conflicting feelings/mixed feelings_2`, method="pearson"),2)

CorAbsorption <- round(cor(InterRater_DF$`Total absorbtion`, InterRater_DF$`Total absorbtion_2`, method="pearson"),2)

CorSpecialAtmosphere <- round(cor(InterRater_DF$`Special atmosphere`, InterRater_DF$`Special atmosphere_2`, method="pearson"),2)

CorWholeness <- round(cor(InterRater_DF$`Experience of wholeness`, InterRater_DF$`Experience of wholeness_2`, method="pearson"),2)

CorLossOfControl <- round(cor(InterRater_DF$`Loss of control`, InterRater_DF$`Loss of control_2`, method="pearson"),2)

CorOwnMemories <- round(cor(InterRater_DF$`Associations to own memories`, InterRater_DF$`Associations to own memories_2`, method="pearson"),2)

CorMeaningOfHumanExistance <- round(cor(InterRater_DF$`Meaning of human life/existance`, InterRater_DF$`Meaning of human life/existance_2`, method="pearson"),2)

CorMeaningOfOwnLife <- round(cor(InterRater_DF$`Meaning of one's own life/existance`, InterRater_DF$`Meaning of one's own life/existance_2`, method="pearson"),2)

CorPersonalGrowth <- round(cor(InterRater_DF$`Personal growth/change`, InterRater_DF$`Personal growth/change_2`, method="pearson"),2)

CorInsight <- round(cor(InterRater_DF$`Insight/attitude change`, InterRater_DF$`Insight/attitude change_2`, method="pearson"),2)

CorAppreciation <- round(cor(InterRater_DF$`Appreciation of feeling and/or experience`, InterRater_DF$`Appreciation of feeling and/or experience_2`, method="pearson"),2)

CorMeaningOfContent <- round(cor(InterRater_DF$`Meaning of the game's content/message/interpretation`, InterRater_DF$`Meaning of the game's content/message/interpretation_2`, method="pearson"),2)

CorDontKnowMeaning <- round(cor(InterRater_DF$`Don't know/can't describe meaning`, InterRater_DF$`Don't know/can't describe meaning_2`, method="pearson"),2)

CorNoMeaning <- round(cor(InterRater_DF$`No meaning`, InterRater_DF$`No meaning_2`, method="pearson"),2)

#CorOtherMeaning <- round(cor(InterRater_DF$`Other meaning`, InterRater_DF$`Other meaning_2`, method="pearson"), 2)

CorHarmony <- round(cor(InterRater_DF$Harmony, InterRater_DF$Harmony_2, method="pearson"),2)

CorDiscrepancy <- round(cor(InterRater_DF$Discrepancy, InterRater_DF$Discrepancy_2, method="pearson"),2)

CorLastingImpression <- round(cor(InterRater_DF$`Lasting impression`, InterRater_DF$`Lasting impression_2`, method="pearson"),2)

CorNeedAgain <- round(cor(InterRater_DF$`Need to experience again`, InterRater_DF$`Need to experience again_2`, method="pearson"),2)

CorHealingExperience <- round(cor(InterRater_DF$`Healing experience`, InterRater_DF$`Healing experience_2`, method="pearson"),2)

CorDisseminate <- round(cor(InterRater_DF$`Want to disseminate the game to others`, InterRater_DF$`Want to disseminate the game to others_2`, method="pearson"),2)

CorUncomfortable <- round(cor(InterRater_DF$`Uncomfortable, unenjoyable`, InterRater_DF$`Uncomfortable, unenjoyable_2`, method="pearson"),2)

```

```{r}
#Combine all Correlations to DF
InterRaterCorrelation <- data.frame(table(CorAbsorption,CorAppreciation,CorBehavior, CorConflictingEmotions, CorCraftsmanship, CorDiscrepancy, CorDisseminate, CorDontKnowMeaning, CorGame, CorGameCharacters, CorHardToDescribe, CorHarmony, CorHealingExperience, CorInsight, CorIntenseEmotions, CorInteractivity, CorLastingImpression, CorLossOfControl, CorMeaningOfContent, CorMeaningOfHumanExistance, CorMeaningOfOwnLife, CorMusic, CorNeedAgain, CorNoMeaning, #CorOtherMeaning, 
                                          CorOtherPeople, CorOtherPerceptions, CorOwnMemories, CorPersonalGrowth, CorPhysicalReactions, CorSimple, CorSpecialAtmosphere, CorSpecificThemes, CorStorytelling, CorUncomfortable, CorUniqueExperience, CorVisualArt, CorWellThoughtoutStory, CorWholeness))

InterRaterCorrelation <- InterRaterCorrelation %>%
  select(!Freq)

InterRaterCorrelation <- melt(InterRaterCorrelation, measure.vars = c(1:length(InterRaterCorrelation)), value.name="Pearsons Phi")

InterRaterCorrelation <- InterRaterCorrelation %>%
  arrange(`Pearsons Phi`)


write.csv(InterRaterCorrelation, "InterRater.csv")
```

`r knitr::kable(InterRaterCorrelation)`







